#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  kill -TERM "$(cat /usr/local/samba/var/run/smbd.pid)" 2>/dev/null
}

trap _term SIGTERM

if [ ! -f /usr/local/samba/var/run/smbd.pid ]; then
  s6-setuidgid root /usr/local/samba/sbin/smbd \
    --configfile=/config/smb.conf \
    --log-basename=/config/logs
fi

wait
