#!/usr/bin/with-contenv bash

# make config file
touch /config/smb.conf

# cleanup pid if it exists
[[ -e /usr/local/samba/var/run/smbd.pid ]] && \
	rm -rf /usr/local/samba/var/run/smbd.pid

# permissions
chown -R abc:abc \
	/config
