#!/usr/bin/with-contenv bash

# make config file
touch /config/smb.conf


# cleanup pid if it exists
[[ -e /config/samba.pid ]] && \
	rm -rf /config/samba.pid

# permissions
chown -R abc:abc \
	/config
